#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : smemstat
Version  : 0.02.11
Release  : 1
URL      : https://github.com/ColinIanKing/smemstat/archive/refs/tags/V0.02.11.tar.gz
Source0  : https://github.com/ColinIanKing/smemstat/archive/refs/tags/V0.02.11.tar.gz
Summary  : smemstat reports memory usage taking into account shared memory regions
Group    : Development/Tools
License  : GPL-2.0
Requires: smemstat-bin = %{version}-%{release}
Requires: smemstat-data = %{version}-%{release}
Requires: smemstat-license = %{version}-%{release}
Requires: smemstat-man = %{version}-%{release}
BuildRequires : pkgconfig(ncursesw)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
smemstat reports the physical memory usage taking into consideration
shared memory. The tool can either report a current snapshot of memory
usage or periodically dump out any changes in memory.

%package bin
Summary: bin components for the smemstat package.
Group: Binaries
Requires: smemstat-data = %{version}-%{release}
Requires: smemstat-license = %{version}-%{release}

%description bin
bin components for the smemstat package.


%package data
Summary: data components for the smemstat package.
Group: Data

%description data
data components for the smemstat package.


%package license
Summary: license components for the smemstat package.
Group: Default

%description license
license components for the smemstat package.


%package man
Summary: man components for the smemstat package.
Group: Default

%description man
man components for the smemstat package.


%prep
%setup -q -n smemstat-0.02.11
cd %{_builddir}/smemstat-0.02.11

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1674581718
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1674581718
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/smemstat
cp %{_builddir}/smemstat-%{version}/COPYING %{buildroot}/usr/share/package-licenses/smemstat/4cc77b90af91e615a64ae04893fdffa7939db84c || :
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/smemstat

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/smemstat

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/smemstat/4cc77b90af91e615a64ae04893fdffa7939db84c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/smemstat.8.gz
